### ISSUE TITLE
fix(ci): typecheck job fails because @protomolecule/eslint-config is not built

### ISSUE THREAD

**Issue by RobEasthope** [RobEasthope/protomolecule#162]
## Problem

The `typecheck` CI job is failing in PR #160 with this error:

```
Error: eslint.config.ts(1,27): error TS2307: Cannot find module '@protomolecule/eslint-config' or its corresponding type declarations.
ELIFECYCLE  Command failed with exit code 2.
Error: Process completed with exit code 1.
```

## Root Cause

The **typecheck** job doesn't build `@protomolecule/eslint-config` before running TypeScript checks, but the root `eslint.config.ts` imports it:

```typescript
import protomolecule from "@protomolecule/eslint-config";
```

### Current CI Workflow

**✅ Lint job** (works correctly):
```yaml
- name: 🏗️ Build eslint-config package
  run: pnpm --filter @protomolecule/eslint-config build

- name: 🔬 Run ESLint
  run: pnpm run lint
```

**❌ Typecheck job** (fails):
```yaml
- name: 🔎 Run TypeScript Check
  run: |
    if ! pnpm run build; then
      # This builds all packages
    fi
    if ! pnpm run typecheck; then
      # This tries to typecheck root, which imports @protomolecule/eslint-config
      # But eslint-config hasn't been built yet!
    fi
```

### Why This Happens

1. `pnpm run build` builds all packages through Turbo
2. But it might skip `@protomolecule/eslint-config` if cached or if there are no changes
3. Then `pnpm run typecheck` runs `tsc --noEmit` at the root
4. Root's `eslint.config.ts` imports `@protomolecule/eslint-config`
5. TypeScript can't find the types because `dist/` folder doesn't exist
6. **Error:** Module not found

### Package Structure

```json
// packages/eslint-config/package.json
{
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",  // ← Needs to be built
      "import": "./dist/index.js"
    }
  }
}
```

### Option 1: Build eslint-config before typecheck (Recommended)

Add an explicit build step in the typecheck job:

```yaml
typecheck:
  name: 🔎 Type Check
  runs-on: ubuntu-latest
  steps:
    - name: ⬇️ Checkout repo
      uses: actions/checkout@v4

    - name: 🔧 Setup Monorepo
      uses: ./.github/actions/setup-monorepo

    - name: 🏗️ Build eslint-config package
      run: pnpm --filter @protomolecule/eslint-config build

    - name: 🔎 Run TypeScript Check
      run: |
        if ! pnpm run build; then
          # Build remaining packages
        fi
        if ! pnpm run typecheck; then
          # Now eslint-config is built, this should work
        fi
```

### Option 2: Always build all packages first

Ensure `pnpm run build` actually builds all packages:

```yaml
- name: 🏗️ Build all packages
  run: pnpm run build --force

- name: 🔎 Run TypeScript Check
  run: pnpm run typecheck
```

### Option 3: Make typecheck depend on build

Update the root `typecheck` script to build first:

```json
// package.json
{
  "scripts": {
    "typecheck": "pnpm build && tsc --noEmit"
  }
}
```

But this might be slower since it rebuilds every time.

## Recommended Fix

**Option 1** is cleanest because it:
- ✅ Explicitly shows the dependency in CI
- ✅ Matches the pattern used in the lint job
- ✅ Only builds what's needed for typecheck
- ✅ Doesn't slow down local development

## Testing

After implementing the fix:

```bash
# Simulate CI environment
rm -rf packages/eslint-config/dist
pnpm install
pnpm run typecheck
# Should fail without the fix

# With fix
pnpm --filter @protomolecule/eslint-config build
pnpm run typecheck
# Should pass
```

## Related

- Failing in PR #160
- Related to `.github/workflows/linting-and-testing.yml` line 89-117
- `@protomolecule/eslint-config` package needs to be built before root typecheck
